auto:	          true

markdown:         rdiscount
pygments:         true
paginate:         1
permalink:        /:year/:month/:day/:title.html

title:            "liuhao's Blog"
url:              http://liuhaoncu.github.io/
feed:             /feed.xml
author:
    name:         dxer
    twitter:      
    key:          dxer
description:      "Only one"
copyright:        "CopryRight GuoJing 2012-2012 by GitHub and Jekyll"
headdesc:         "Liuhao的博客"
headkeys:         "设计,开发,思考,生活,电影,音乐"
